image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  
flake8:
  allow_failure: true
  stage: Static Analysis
  script:
  - echo 'test'
