# Generated by Django 2.2 on 2019-06-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_answer'),
        ('blog', '0005_auto_20190524_1901'),
    ]

    operations = [
    ]
