# Generated by Django 2.2 on 2019-06-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190609_1050'),
        ('blog', '0007_post_thumb'),
    ]

    operations = [
    ]
