# Generated by Django 2.2 on 2019-06-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_likes'),
        ('blog', '0005_auto_20190524_1901'),
        ('blog', '0004_answer'),
    ]

    operations = [
    ]
