# Generated by Django 2.2 on 2019-06-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190609_1240'),
        ('blog', '0008_merge_20190611_1004'),
    ]

    operations = [
    ]
