# Generated by Django 2.2 on 2019-06-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190612_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['date_posted'], 'verbose_name': 'question'},
        ),
    ]
