# Generated by Django 2.2 on 2019-06-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190613_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
    ]
