# Generated by Django 2.2 on 2019-06-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default='Anonymous', max_length=120, null=True),
        ),
    ]
