# Generated by Django 2.2 on 2019-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190616_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_user',
            field=models.BooleanField(default=False),
        ),
    ]
