# Generated by Django 2.2 on 2019-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_approved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newtype',
            field=models.CharField(default='none', max_length=120, null=True),
        ),
    ]
