# Generated by Django 2.2 on 2019-06-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_newtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newtype',
        ),
    ]
