# Generated by Django 2.2 on 2019-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_newtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Author', 'Author'), ('Reader', 'Reader')], default='Anonymous', max_length=20, null=True),
        ),
    ]
