# Generated by Django 2.2 on 2019-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190619_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_role',
            field=models.BooleanField(default=False),
        ),
    ]
