# Generated by Django 2.2 on 2019-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_new_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Author', 'Author'), ('Reader', 'Reader')], default='none', max_length=20, null=True),
        ),
    ]
