# Generated by Django 2.2 on 2019-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190620_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_type',
            field=models.CharField(default='Anonymous', max_length=20, null=True),
        ),
    ]
